/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.JPanel;
import java.util.regex.*;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.awt.Image;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import model.Item;
import util.DatabaseConnector;

/**
 *
 * @author Admin
 */
public class InventoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormPanel
     */
    private JPanel bottomPanel;
    private MainFrame mainFrame;
    public InventoryPanel(JPanel bottomPanel, MainFrame mainFrame) {
        initComponents();
        this.bottomPanel = bottomPanel;
        this.mainFrame = mainFrame;
    }
    
    private List<Item> listOfItems;
    private Item selectedItem;

    public InventoryPanel(Item newItem) {
        initComponents();
        refreshListOfItems();
    }
    
    
    public void setListOfItems(List<Item> listOfItems){
        this.listOfItems=listOfItems;
    }
    
    public void refreshListOfItems(){
        this.listOfItems = DatabaseConnector.getAllItemsWithCriteria(null);
        populateTable();
    }
    
    public void clearFormFields() {
        ItemNameTextField.setText("");
        ManufacturerTextField.setText("");
        SKNTextField.setText("");
        WarrantyTextField.setText("");
        categoryTypeComboBox.setSelectedItem(null);
        YesRadioButton.setSelected(false); 
        NoRadioButton.setSelected(false);
        
        
    }
   public void populateTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);
            for (Item u : this.listOfItems) {
                Object[] row = new Object[7];
                row[0] = u.getId();
                row[1] = u.getItemName();
                row[2] = u.getManufacturer();
                row[3] = u.getSkuNo();
                row[4] = u.getWarranty();
                row[5] = u.getCategory();
                row[6] = u.getActive();
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
   
    private void clearFields() {
        listOfItems = null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        imageLabel = new javax.swing.JLabel();
        ManufacturerLabel = new javax.swing.JLabel();
        categoryTypeComboBox = new javax.swing.JComboBox<>();
        YesRadioButton = new javax.swing.JRadioButton();
        NoRadioButton = new javax.swing.JRadioButton();
        WarrantyLabel = new javax.swing.JLabel();
        CategoryTypeLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        WarrantyTextField = new javax.swing.JTextField();
        SKNLabel = new javax.swing.JLabel();
        ItemNameTextField = new javax.swing.JTextField();
        SKNTextField = new javax.swing.JTextField();
        ManufacturerTextField = new javax.swing.JTextField();
        activeLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        itemNameLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(153, 153, 255));
        setMinimumSize(new java.awt.Dimension(700, 700));

        ManufacturerLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        ManufacturerLabel.setText("Manufacturer");

        categoryTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electronics", "Soft Toys", "Puzzles" }));
        categoryTypeComboBox.setSelectedIndex(-1);

        genderButtonGroup.add(YesRadioButton);
        YesRadioButton.setText("Yes");
        YesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesRadioButtonActionPerformed(evt);
            }
        });

        genderButtonGroup.add(NoRadioButton);
        NoRadioButton.setText("No");

        WarrantyLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        WarrantyLabel.setText("Warranty Duration");

        CategoryTypeLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        CategoryTypeLabel.setText("Category");

        submitButton.setText("Save");
        submitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        submitButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        WarrantyTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                WarrantyTextFieldKeyReleased(evt);
            }
        });

        SKNLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        SKNLabel.setText("SKU Number");

        ItemNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemNameTextFieldActionPerformed(evt);
            }
        });
        ItemNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ItemNameTextFieldKeyReleased(evt);
            }
        });

        SKNTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SKNTextFieldKeyReleased(evt);
            }
        });

        ManufacturerTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ManufacturerTextFieldKeyReleased(evt);
            }
        });

        activeLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        activeLabel.setText("Active");

        titleLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Update Inventory");

        itemNameLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        itemNameLabel.setText("Item Name");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Item Name", "Manufacturer", "SKU Number", "Category", "Warranty Status", "Active"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(deleteButton)
                .addGap(225, 225, 225))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SKNLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(WarrantyLabel)
                                    .addComponent(ManufacturerLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itemNameLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(CategoryTypeLabel)
                                .addComponent(activeLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editButton)
                                .addGap(46, 46, 46)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ManufacturerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SKNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WarrantyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(YesRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NoRadioButton))
                                .addComponent(categoryTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(248, 248, 248))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(404, 404, 404)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(106, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(titleLabel)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton)
                    .addComponent(editButton))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemNameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManufacturerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManufacturerLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SKNLabel)
                    .addComponent(SKNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WarrantyLabel)
                    .addComponent(WarrantyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(categoryTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CategoryTypeLabel)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesRadioButton)
                    .addComponent(NoRadioButton)
                    .addComponent(activeLabel))
                .addGap(17, 17, 17)
                .addComponent(submitButton)
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(633, 633, 633)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(44, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void YesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YesRadioButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        Item newItem = new Item();
        newItem.setItemName(ItemNameTextField.getText());
        newItem.setManufacturer(ManufacturerTextField.getText());
        newItem.setSkuNo(SKNTextField.getText());
        newItem.setWarranty(WarrantyTextField.getText());
        newItem.setCategory(categoryTypeComboBox.getSelectedItem().toString());
        if (YesRadioButton.isSelected() == true) {
            newItem.setActive("Yes");
        } else if (NoRadioButton.isSelected() == true) {
            newItem.setActive("No");
        }


        try {
//insert into db
            DatabaseConnector.editUser(selectedItem, newItem);
            JOptionPane.showMessageDialog(null, "Item updated!", "Successful update", JOptionPane.PLAIN_MESSAGE);
            //clearFields();
            //populateTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        this.refreshListOfItems();
        this.clearFormFields();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void WarrantyTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WarrantyTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_WarrantyTextFieldKeyReleased

    private void ItemNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemNameTextFieldActionPerformed

    }//GEN-LAST:event_ItemNameTextFieldActionPerformed

    private void ItemNameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ItemNameTextFieldKeyReleased
        // TODO add your handling code here:
//        String pattern = "^[a-zA-Z]{0,15}$";
//        Pattern pat = Pattern.compile(pattern);
//        Matcher match = pat.matcher(ItemNameTextField.getText());
//        if(!match.matches()){
//            fLabel.setText("Enter only text data");
//        }
//        else{
//            fLabel.setText(null);
//        }
    }//GEN-LAST:event_ItemNameTextFieldKeyReleased

    private void SKNTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SKNTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_SKNTextFieldKeyReleased

    private void ManufacturerTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ManufacturerTextFieldKeyReleased
        // TODO add your handling code here:
//        String pattern = "^[a-zA-Z]{0,30}$";
//        Pattern pat = Pattern.compile(pattern);
//        Matcher match = pat.matcher(ManufacturerTextField.getText());
//        if(!match.matches()){
//            lLabel.setText("Enter only text data");
//        }
//        else{
//            lLabel.setText(null);
//        }
    }//GEN-LAST:event_ManufacturerTextFieldKeyReleased

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed

        int selectedIndex = jTable2.getSelectedRow();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this, "Please select an item to edit", "Cannot edit item", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        selectedItem = listOfItems.get(selectedIndex);
        ItemNameTextField.setText(selectedItem.getItemName());
        ManufacturerTextField.setText(selectedItem.getManufacturer());
        SKNTextField.setText(selectedItem.getSkuNo());
        WarrantyTextField.setText(selectedItem.getWarranty());
        categoryTypeComboBox.setSelectedItem(selectedItem.getCategory());
        if(selectedItem.getActive()!=null && selectedItem.getActive().equals("Yes"))
        {
           YesRadioButton.setSelected(true); 
        }else {
            NoRadioButton.setSelected(true);
        }
  
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int selectedIndex = jTable2.getSelectedRow();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this, "Please select an item to delete", "Cannot delete item", JOptionPane.PLAIN_MESSAGE);
            return;
        }
        try {
            selectedItem = listOfItems.get(selectedIndex);
            DatabaseConnector.deleteItem(selectedItem);
            JOptionPane.showMessageDialog(null, "Item deleted successfully", "Successfully deleted", JOptionPane.PLAIN_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        this.refreshListOfItems();
    }//GEN-LAST:event_deleteButtonActionPerformed
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CategoryTypeLabel;
    private javax.swing.JTextField ItemNameTextField;
    private javax.swing.JLabel ManufacturerLabel;
    private javax.swing.JTextField ManufacturerTextField;
    private javax.swing.JRadioButton NoRadioButton;
    private javax.swing.JLabel SKNLabel;
    private javax.swing.JTextField SKNTextField;
    private javax.swing.JLabel WarrantyLabel;
    private javax.swing.JTextField WarrantyTextField;
    private javax.swing.JRadioButton YesRadioButton;
    private javax.swing.JLabel activeLabel;
    private javax.swing.JComboBox<String> categoryTypeComboBox;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel itemNameLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

}
